# Generated by Django 2.2.7 on 2019-11-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('isOrg', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
                ('host_org', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(blank=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=200)),
                ('ownerID', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Eventss',
        ),
    ]
