# Generated by Django 2.2.7 on 2019-11-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
