# Generated by Django 2.2.7 on 2019-12-08 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_end_date'),
        ('events', '0004_auto_20191120_1539'),
    ]

    operations = [
    ]
