# Generated by Django 2.2.7 on 2019-12-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_link'),
        ('events', '0005_merge_20191208_0251'),
    ]

    operations = [
    ]
